### ISSUE TITLE
CfC: Adopt "A perspective on Media & Entertainment for the Web" document into the IG

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#12]
This is a call for consensus based on the discussion during the IG call on December 4 [1] about the proposal to adopt Francois' "A perspective on Media & Entertainment for the Web" document [2] into the Interest Group with the goal of iterating on the document, and potentially publishing as an Interest Group Note.

Please respond before the end of Tuesday 25 December.

Positive responses are encouraged (e.g., as a "thumbs-up" on this GitHub issue), silence will be taken as consent. If you disagree, please leave a comment to indicate your rationale.

[1] https://www.w3.org/2018/12/04-me-minutes.html#item03
[2] https://tidoust.github.io/me-vision

**Comment by gmandyam** [comment]
:thumbsup:

**Comment by chrisn** [comment]
Thanks for the responses. The call for consensus passes with no objections. We'll migrate the document to the W3C GitHub organisation and use GitHub issues to manage updates.

**Comment by tidoust** [comment]
Status update: I transitioned the repository over to the W3C organization and associated the document with the Media & Entertainment IG. New repository:
https://github.com/w3c/me-vision/

Unfortunately, the transition means that the previous URL for the document is gone (GitHub redirects the repo URL but not the published URL). New URL for the document:
https://w3c.github.io/me-vision/
