### ISSUE TITLE
CfC: Publish Media Timed Events as an Interest Group Note

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#13]
This is a call for consensus to publish the use cases and requirements document [1] from the Media Timed Events Task Force as an Interest Group Note, following a Task Force resolution taken on the 17th December call [2].

The intention is to publish as a snapshot in time and invite review from Interest Group members. The document may be updated based on feedback and further iteration.

Please respond before the end of Tuesday 25 December.

Positive responses are encouraged (e.g., as a "thumbs-up" on this GitHub issue), silence will be taken as consent. If you disagree, please leave a comment to indicate your rationale.

[1] https://w3c.github.io/me-media-timed-events/
[2] https://www.w3.org/2018/12/17-me-minutes.html

**Comment by gmandyam** [comment]
:thumbsup:

**Comment by chrisn** [comment]
Thanks for the responses. The call for consensus passes with no objections. As Mark left a number of good suggestions to improve the document [here](https://github.com/w3c/me-media-timed-events/issues/29). I propose to resolve these, and then publish the Note. I suggest we use 'media-timed-events' as the short name.

**Comment by chrisn** [comment]
The document has now been published: https://www.w3.org/TR/media-timed-events/
