### ISSUE TITLE
MEIG Con-call (8th Jan): Case studies from China Mobile - Migu

### ISSUE THREAD

**Issue by gsimcard** [w3c/media-and-entertainment#14]
Hi all,

Here I'd like to put the MEIG_case studies_CMCC powerpoint for better issue tracking. Looking forward to your input before conference call on 8th January. Thanks.

Best wishes for 2019.

Song XU
China Mobile - Migu

[20181230MEIG_Case studies_CMCC.pptx](https://github.com/w3c/media-and-entertainment/files/2718053/20181230MEIG_Case.studies_CMCC.pptx)

**Comment by chrisn** [comment]
Here are the updated slides in [PowerPoint](https://github.com/w3c/media-and-entertainment/files/2744890/W3C_MEIG_Case.studies_CMCC.pptx) and [PDF](https://github.com/w3c/media-and-entertainment/files/2744889/W3C_MEIG_Case.studies_CMCC.pdf) formats. The PowerPoint copy has embedded videos of the bullet screen use case.
