### ISSUE TITLE
CfC: Rechartering the Media & Entertainment Interest Group

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#17]
This is a call for consensus to recharter the Interest Group. The current charter for the Media & Entertainment Interest Group ends on 30 April 2019.

Please review the draft Charter [1], which we have updated to reflect our current activities. There are no major changes. Please respond before the end of Friday 8th March. Positive responses are encouraged (e.g., as a "thumbs-up" on this GitHub issue), silence will be taken as consent. If you disagree, or have feedback on the Charter, please comment here or on our mailing list [2].

I also want to take this opportunity to invite your feedback on how the IG is working. What would you like to see happen in the Interest Group? Do you have feedback on our monthly calls or F2F meetings? Your input is very welcome.

[1] https://w3c.github.io/media-and-entertainment/charters/charter-2019.html
[2] https://lists.w3.org/Archives/Public/public-web-and-tv/

**Comment by mavgit** [comment]
I added my thumbs up to the new IG charter Issue #16 and I encourage you all to do so.

We're about to start an exciting phase of work defining the next phase of HTML5 Media API's, which will likely lead to much higher activity in the M&E IG.

The IG had very high activity during the development of HTML5 Media API's "1.0", where we represented media expert and media industry requirements in the development of several media specs, including HTML5, EME, MSE, IMSC1 and Web Crypto.

After a few years of moderate IG activity while HTML5 Media was rolled out, there are now a large number of new and updated specs that will be moving from incubation to final specs to create HTML5 Media API's "1.x" or "2.0". It's likely that the M&E IG will likewise again be very active driving these APIs. It's an exciting time!

Please add your thumbs up and any other comments on issue #16

**Comment by chrisn** [comment]
The call for consensus passed, please see Mark's message [here](https://lists.w3.org/Archives/Public/public-web-and-tv/2019Mar/0010.html).
