### ISSUE TITLE
CfC: Start a Bullet Chatting Task Force

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#29]
This is a call for consensus to start a Task Force in the Media & Entertainment Interest Group to focus on [Bullet Chatting][1], which was present at our previous calls on [8 Jan 2019][2] and [6 Aug 2019][3], and at [TPAC 2019][4].

The Task Force will be responsible for gathering use cases and deriving technical requirements for Bullet Chatting, which refers to comments or annotations overlaid on the video playback screen, synced to a specific playback time.

Technical requirements would then be taken to the relevant Working Groups, e.g., Timed Text Working Group, Media Working Group, WHATWG, or solutions developed in the dedicated Bullet Chatting Community Group.

We think that starting this work in the M&E IG would help bring broader input to help with technical requirements and gap analysis.

Please respond before the end of Tuesday 3rd December. Positive responses are encouraged (e.g., as a "thumbs-up" on this GitHub issue), silence will be taken as consent. If you disagree, or have other suggestions or feedback, please comment here or on our [mailing list][5].

[1]: https://github.com/w3c/media-and-entertainment/issues/15
[2]: https://www.w3.org/2019/01/08-me-minutes.html
[3]: https://www.w3.org/2019/08/06-me-minutes.html
[4]: https://www.w3.org/2019/09/16-me-minutes.html#item11
[5]: https://lists.w3.org/Archives/Public/public-web-and-tv

**Comment by peipeiguo** [comment]
:+1:

**Comment by chrisn** [comment]
The CfC passed, and so the Task Force is now active. Please see the [TF wiki page][1] for details.

[1]: https://www.w3.org/2011/webtv/wiki/Main_Page/Bullet_Chatting_TF
