### ISSUE TITLE
API for client-side video editing (MediaBlob)

### ISSUE THREAD

**Issue by palemieux** [w3c/media-and-entertainment#38]
> Currently editing video within the browser is a very complex task as there isn't any straight forward approach to decoding the encoded video file to produce a raw stream that can do common video editing capabilities such as trimming or concatenation.

https://github.com/w3ctag/design-reviews/issues/514
https://github.com/WICG/video-editing

_This issue tracks a media-related issue/proposal/work item/discussion_

**Comment by palemieux** [comment]
I have shared my thoughts re: media editing API at:

https://github.com/WICG/video-editing/issues/13#issuecomment-638426885

**Comment by ykh015** [comment]
[MediaBlob.pptx](https://github.com/w3c/media-and-entertainment/files/4882205/MediaBlob.pptx)
Here are the slides we presented during the June meeting.

**Comment by chrisn** [comment]
Thank you, @ykh015!

**Comment by chrisn** [comment]
There is further discussion in the blink-dev [Intent to Prototype thread][1].

[1]: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/3eac-HVygFY

**Comment by chrisn** [comment]
@ykh015 We're wondering what the status of the MediaBlob proposal is, and in particular in relation to Web Codecs? There was some discussion in https://github.com/WICG/video-editing/issues/13 about the benefits of a playlist based approach for efficient media editing. What input would you want to see from media companies to help move things forward?

**Comment by chrisn** [comment]
Closing this, as I have feedback from @ykh015 to say that Web Codecs is now their preferred solution for media editing scenarios.
