### ISSUE TITLE
Media & Entertainment IG rechartering

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#43]
The [current charter][1] for the Media & Entertainment Interest Group ends on 30 April 2021.

The co-chairs are now considering options for rechartering our group. 

In our current charter period, we have:

* Published the [Requirements for Media Timed Events][2] IG Note
* Started incubation of the [DataCue API][3] in the Web Platform Incubation CG (WICG)
* Started work on a new document, [Media Integration Guidelines][4]
* Restarted activity in the [Color on the Web Community Group][5], focusing on improving on support for HDR color on the Web
* Started a gap analysis for browser features to support bullet chatting
* Started initial discussions on media production use cases and requirements, including review of the [Improved client side video editing][6] WICG proposal
* Discussed alignment of media specifications with industry needs as input for the creation of the [Media WG][7] (MSE/EME, Media Capabilities, Picture-in-Picture, Media Session)
* Discussed alignment of WebTransport with streaming needs as input for the creation of the [WebTransport WG][8]

Our current active topics include development of the Media Integration Guidelines, and continuing the bullet chatting gap analysis.

Aside from this, our group is fairly quiet at the moment. So we want to hear your input, specifically on the goals and priorities we should work towards in the next 2-year charter period.

Consistent with our group's mission **to identify use cases and requirements that existing and/or new specifications need to meet to achieve a tighter support of media services on the Web**, some of our own thoughts are:

* Continue to review developments in relevant WGs (Media, Web Transport, etc), and new API proposals, such as Web Codecs, to consider alignment with media industry needs
* Evaluate practical issues with building interactive TV applications using web technologies, and propose changes in the relevant WGs where needed
* Continue the requirements and gap analysis for media production use cases
* Propose options for frame accurate synchronization of web content with media streams (see [issue #4][9])
* Consider the potential impact of proposed web platform changes to improve user privacy, e.g., [Privacy Sandbox][10], and [work items in the Privacy CG][11]
* In collaboration with the [Web & Networks IG][12], look at how web based media streaming can use new capabilities in 5G networking
* Consider discovery, control, and accessing content on media devices in the home network, e.g., using [Web of Things][13]

All of this, though, needs active participants who can help drive the discussion. As mentioned, we want to hear from you. 

Please share your perspective on these, or any other web media related topics that are important to you.

You are welcome to leave a comment here, or please contact the co-chairs directly.

[1]: https://www.w3.org/2019/06/me-ig-charter.html
[2]: https://www.w3.org/TR/media-timed-events/
[3]: https://github.com/wicg/datacue
[4]: https://w3c.github.io/me-media-integration-guidelines/
[5]: https://www.w3.org/groups/cg/colorweb
[6]: https://github.com/WICG/video-editing
[7]: https://w3.org/groups/wg/media
[8]: https://w3.org/groups/wg/webtransport
[9]: https://github.com/w3c/media-and-entertainment/issues/4
[10]: https://www.chromium.org/Home/chromium-privacy/privacy-sandbox
[11]: https://privacycg.github.io/charter.html#work-items
[12]: https://www.w3.org/groups/ig/web-networks
[13]: https://www.w3.org/WoT/IG/

**Comment by igarashi50** [comment]
> Consistent with our group's mission to identify use cases and requirements that existing and/or new specifications need to meet to achieve a tighter support of media services on the Web,

The group mission is very good to facilitate the collaboration of media related activities in W3C.  I also hope that participants in all groups which work on media technologies, e.g. Color on the Web CG, WebMedia WG, Web Transport WG, will make good use of the M&E IG to communicate with the media industry and related SDOs.

**Comment by wilaw** [comment]
The [CTA WAVE project](https://github.com/w3c/media-and-entertainment/issues/43) has an agenda of promoting web media via [specifications](https://cta.tech/Resources/Standards/WAVE-Project#specs) and [tests suites](https://cta.tech/Resources/Standards/WAVE-Project#tests) for HTML, Content preparation, Device Playback and HLS/DASH Interop.  To this end, its mission to some degree overlaps that of the MEIG.  WAVE has 56 member companies, many of whom are also members of MEIG. As part of the new charter it may be good to figure out:

- how to formalize relationships between the two groups.
- set scope of interest to avoid duplicate and wasted effort.
- how to best leverage the active participants in both groups to advance web media.

**Comment by chrisn** [comment]
Thanks @wilaw, I'd be very interested to discuss further to figure that out.

**Comment by digitaltvguy** [comment]
Comcast/NBCU/Sky can participate in Color on the Web Community Group.

**Comment by ytakio** [comment]
Thank you for always letting me participate.

> Continue to review developments in relevant WGs (Media, Web Transport, etc), and new API proposals, such as Web Codecs, to consider alignment with media industry needs

Above item is important for me. While there are many WGs and WICG proposals related to media in W3C, I think that each spec should be general and co-operative in order to enrich the Web media platform. For that, it is important to review them designed by each group (not only within W3C) from several point of view. However, I also feel that it is very hard for individual to track all.

Many media experts from various fields have participated in this M&E IG, so this IG is very appropriate to review and discuss them. I could also personally found some requests by Some topic and discussions IG provided. Therefore, I would be happy if we could continue to review and discuss spec or/and use-cases.

I'm sorry that I don't have always concrete use-cases or requests, but I believe that getting the Web as a media platform better will naturally promote everyone's business.

**Comment by tidoust** [comment]
Link to draft of a renewed charter:
https://w3c.github.io/media-and-entertainment/charters/charter-2021.html

**Comment by chrisn** [comment]
The new charter was approved on 11 June 2021, the group is now chartered until 30 April 2023.

https://www.w3.org/2021/06/me-ig-charter.html
