### ISSUE TITLE
Multicast Receive API proposal

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#44]
I have just seen this Chromium [Intent to Prototype][1]. The proposal is for a source-specific multicast receive API, where large scale live video distribution is one of the primary use cases. Please refer to the [Explainer][2] for details. There is also a [WICG Discourse Thread][3] (from 2019).

*This issue tracks a media-related issue/proposal/work item/discussion*

[1]: https://groups.google.com/a/chromium.org/g/blink-dev/c/8sNTXCoggcQ/m/sFr7FOteBAAJ
[2]: https://github.com/GrumpyOldTroll/wicg-multicast-receiver-api/blob/master/explainer.md
[3]: https://discourse.wicg.io/t/proposal-multicastreceiver-api/3939

**Comment by acbegen** [comment]
The DORMS proposal is quite interesting. Just to give an idea about a proposal we had years back is [here](https://www.ietf.org/archive/id/draft-singer-appsawg-mcast-url-00.txt).

**Comment by chrisn** [comment]
See follow-up discussion on the Chromium net-dev mailing list [here][1].

[1]: https://groups.google.com/a/chromium.org/g/net-dev/c/TjbMyPKuRHs/m/01MYKqsSGgAJ

**Comment by chrisn** [comment]
This work is continuing in the new [Multicast Community Group][1], see the [Charter][2] . If this topic is of interest to you, please join the group. Details of an initial CG meeting on 23 June were posted [here][3].

[1]: https://www.w3.org/community/multicast/
[2]: https://w3c.github.io/multicast-cg/multicast-cg-charter.html
[3]: https://lists.w3.org/Archives/Public/public-web-and-tv/2021Jun/0031.html

**Comment by chrisn** [comment]
Here are the minutes from the first Multicast CG meeting: https://www.w3.org/2021/06/23-multicast-minutes.html

**Comment by chrisn** [comment]
Jake (@GrumpyOldTroll) announced in October 2022 that he's stepping down from chairing the Multicast CG: https://lists.w3.org/Archives/Public/public-multicast/2022Oct/0000.html. This means no-one is currently driving this work. If there is interest to continue. please comment here and we'll follow up. But for now, I'll close this issue.
