### ISSUE TITLE
[charter] Weird coordination/HR text

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-and-entertainment#52]
I appreciate why you didn't take the charter template text re: horizontal review - this is, after all, an IG that doesn't produce specifications. 

That said, the replacement text in section 4 is odd.

It calls for HR for "all topics discussed within the group".  I suspect that should instead be "all documents produced by the group".  It then goes on to talk about "specifications", including mentioning "...major standards-track document transition...".  I would be happy to see HR review on the IG's Notes, but if they're indeed not producing *specifications*, we should clean this text up.

Likewise, section 3.2 should probably drop "Test suite and implementation report for the specification".

**Comment by tidoust** [comment]
Draft charter updated to get back to the appropriate boilerplate section. The mention of test suite has also been removed. I'm closing this issue accordingly. @samuelweiler, please reopen if you believe further changes are required.
