### ISSUE TITLE
CfC: Rechartering the Media & Entertainment Interest Group

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#57]
This is a call for consensus to recharter the Media & Entertainment Interest Group. The current charter ends on 30 April 2021.

Please review the [draft Charter][1]. The differences from the 2019 charter can be seen [here][2].

The main changes include:

* Updated to reflect our current activities
* Clarifying the Scope section by moving the list of tasks the IG may perform to Success Criteria
* Removed Media Timed Events as current work item, and added Media Integration Guidelines
* Updated the Coordination section per the latest W3C charter template, and the list of related W3C and external groups

Following feedback from [our last meeting][3]:

* The group will continue to track developments of media timed events APIs in other groups (WICG, WHATWG, Timed Text Working Group)
* We would prefer to writing something on the position of our group in relation to other industry groups outside the charter, e.g., on our [public website][4] or [GitHub][5]. We expect this to take some time, and want to avoid delaying the rechartering process.

Please respond before the end of Friday 26th March. Please reply to this GitHub issue to indicate your support (either leave a comment, or give a "thumbs-up" on this issue). If you disagree, or have feedback on the Charter, please comment here or on our [mailing list][6].

[1]: https://w3c.github.io/media-and-entertainment/charters/charter-2021.html
[2]: https://w3c.github.io/media-and-entertainment/charters/diff-2021-2019.html
[3]: https://www.w3.org/2021/03/02-me-minutes.html
[4]: https://www.w3.org/2011/webtv/
[5]: https://github.com/w3c/media-and-entertainment
[6]: https://lists.w3.org/Archives/Public/public-web-and-tv/

**Comment by ytakio** [comment]
Thank you for CfC.

How about adding `WebTransport WG` in "4.1 W3C Group" ?

We already have issue #25 and, WebCodecs + WebTransport may be used for media exchange/transfer (including low latency) use cases.

**Comment by chrisn** [comment]
Closing this, as the charter is now under AC review. If your company has not voted yet, please ask your AC representative to do so. Your vote and feedback is important in the charter approval process. The deadline is 28 May.
