### ISSUE TITLE
[charter] link to list of tracked items?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/media-and-entertainment#59]
Section 3:

> The group will also maintain a public list of the media features on the Web that it is tracking and investigating.

Can we provide a link to that list?

**Comment by tidoust** [comment]
I believe the idea behind this was to use the [Overview of Media technologies of the Web](https://w3c.github.io/web-roadmaps/media/). However, it hasn't really been maintained up-to-date and does not necessarily reflect the list of features that the group is tracking.

An alternative would be to link to the group's issue tracker, which is more current, but also a bit messy and probably does not need to be called out in the charter.

I guess the easiest way to resolve this is to drop the sentence altogether. I'll prepare a pull request to that effect.

**Comment by chrisn** [comment]
We have started to use the `tracking` label on GitHub issues for this purpose, but it's by no means a complete list. I'd agree that it probably does not need to go in the charter, so I'm OK with removing that sentence.
