### ISSUE TITLE
Charter: Editorial nits 

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/media-and-entertainment#64]
In the Success Criteria section, 2 proposed editorial changes:

### Suggesting to existing WGs

> Suggesting existing Working Groups to include particular topics in their scope as appropriate

should be:

> Suggesting to existing Working Groups that they include particular topics in their scope as appropriate

### Giving _equal_ consideration?

> Ensuring issues of accessibility, device independence, internationalization, performance, privacy, and security are given equal consideration in all discussions and outcomes.

equality isn't measurable here, I think the important thing is that they are all considered, so suggest:

> Ensuring issues of accessibility, device independence, internationalization, performance, privacy, and security are all given due consideration in all discussions and outcomes.

**Comment by chrisn** [comment]
This seems fine to me. @ashimura, @tidoust - do you see any potential issues from horizontal review groups if we make this proposed change.

**Comment by tidoust** [comment]
That seems fine to me as well, and editorial in essence, so I don't think that can trigger any sort of issue.

(FYI, the charter sent to the AC for review today is a frozen version of the charter here, so changes won't be immediately reflected in it. That's a "feature", charters are not really supposed to change during the review period)
