### ISSUE TITLE
Charter: Suggest adding Audio Description CG

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/media-and-entertainment#65]
In 4.1 W3C Groups suggest adding Audio Description CG, https://www.w3.org/community/audio-description/ 

Mission: To create an open standard file format to support audio description all the way from scripting to mixing. 

The main deliverable of the ADCG was the AD Profile of TTML2, which is now in scope of TTWG, however I think it would still be a useful community to include.

**Comment by chrisn** [comment]
Resolved via #66
