### ISSUE TITLE
Overview of Media Technologies for the Web updates

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#7]
There are a few areas in [Overview of Media Technologies for the Web](https://w3c.github.io/web-roadmaps/media/) document that could use updating:

* [Media Control](https://w3c.github.io/web-roadmaps/media/control.html): This page should now refer to the [WebXR Device API](https://immersive-web.github.io/webxr/), rather than WebVR.
* [Media Distribution](https://w3c.github.io/web-roadmaps/media/distribution.html) and [Media Processing](https://w3c.github.io/web-roadmaps/media/processing.html): Add details to these pages to the work in WICG to update Media Source Extensions to support [codec switching](https://github.com/WICG/media-source), e.g., for ad insertion.
* [Media Orchestration](https://w3c.github.io/web-roadmaps/media/synchronized.html): This page should mention the [Media Timed Events TF](https://github.com/w3c/me-media-timed-events) under "Exploratory work".

**Comment by tidoust** [comment]
I prepared a [pull request](https://github.com/w3c/web-roadmaps/pull/306) to update the contents of the document as suggested. The pull request also proposes other changes to take recent discussions into account:

- Media Distribution and Media Processing: update MSE description to better highlight adaptive streaming
- Media Distribution: update part on WebRTC to mention WebRTC distribution
- Media Distribution: mention discussion on push and multicast in "Features not covered by on-going work" section

**Comment by chrisn** [comment]
Thanks for making these updates, Francois.
