### ISSUE TITLE
TPAC 2021 Planning

### ISSUE THREAD

**Issue by chrisn** [w3c/media-and-entertainment#71]
Do we want to meet or organise any joint meetings during TPAC 2021?

18-22 October: Breakout sessions
25-29 October: Group meetings and Joint group meetings

https://www.w3.org/wiki/TPAC/2021/GroupMeetings

Which groups do we want to have joint meetings with, or want to have joint meetings with us? Please reply to this GitHub issue with suggestions.

**Comment by JohnRiv** [comment]
I think what is going on with [MiniApps](https://w3c.github.io/miniapp/white-paper/) has some interesting parallels with app development on smart TVs, set-top boxes and other embedded devices. A joint meeting with the MiniApps [CG](https://www.w3.org/community/miniapps/) or [WG](https://www.w3.org/2021/miniapps/) could be interesting.

I need another month or so to determine what the agenda/goals of that meeting would be, but I wanted to at least put the idea out there now so others can offer their related ideas.

**Comment by chrisn** [comment]
## Media & Entertainment IG TPAC Meetings

For TPAC 2021 we have two meetings planned, for input from related industry groups. We will update this issue as details are confirmed.

### Meeting 1: Topics from CTA WAVE / HbbTV / ATSC

| Location | Date & Time |
| -------- | ----------- |
| San Francisco (U.S.A.) | Monday, October 25, 07:00 - 09:00 PDT |
| Boston (U.S.A.) | Monday, October 25, 10:00 - 12:00 EDT |
| London (United Kingdom) | Monday, October 25, 15:00 - 17:00 GMT+1 |
| Paris (France) | Monday, October 25, 16:00 - 18:00 GMT+2 |
| Beijing (China) | Monday, October 25, 22:00 - 00:00 GMT+8 |
| Tokyo (Japan) | Monday, October 25, 23:00 - 01:00 GMT+9 |
| Corresponding UTC (GMT) | Monday, October 25, 21:00 UTC |

#### Agenda 

- https://github.com/w3c/media-and-entertainment/issues/79
- Other topics TBD

### Meeting 2: Topics from IPTV Forum Japan

Meeting time to be confirmed

#### Agenda

- TBD

**Comment by chrisn** [comment]
Minutes and summary from the TPAC 2021 MEIG meetings can be found [here](https://lists.w3.org/Archives/Public/public-web-and-tv/2021Nov/0001.html).
