### ISSUE TITLE
M&E IG TPAC 2018 Schedule

### ISSUE THREAD

**Issue by mavgit** [w3c/media-and-entertainment#8]
Here's a first draft schedule from the [Media & Entertainment Interest Group (MEIG) Chairs](team-webandtv-chairs@w3.org) for the [MEIG meeting](https://www.w3.org/2018/10/TPAC/schedule.html#Monday) at [TPAC 2018](https://www.w3.org/2018/10/TPAC/) in Lyon. Please add comments on this issue for additions and/or changes:

# Morning session:

1. Welcome and introduction - IG Chairs
2. Agenda bash - IG Chairs
3. [Media Timed Events Task Force (MTETF)](https://www.w3.org/2011/webtv/wiki/Main_Page/Media_Timed_Events_TF) [report](https://w3c.github.io/me-media-timed-events/) - Giridhar Mandyam
4. TV industry standards updates
   - [ATSC](https://www.atsc.org/standards/atsc-3-0-standards/) - Giridhar Mandyam
   - [HbbTV](https://www.hbbtv.org/) - TBD
   - [IPTV Forum Japan](http://www.iptvforum.jp/en/) - TBD
   - [CTA WAVE](https://cta.tech/Research-Standards/Standards-Documents/WAVE-Project/WAVE-Project.aspx) - Mark Vickers
   - others? 
5. Review of media related topics in W3C
   - pointers to other media related sessions at TPAC
6. Open discussion on new media web platform requirements & suggestions for 2019 MEIG Task Forces

# Afternoon session:

7. Joint meetings
   - [Timed Text Working Group](https://github.com/w3c/Web-and-TV-IG/issues/)
   - WICG work on EME & MSE - Mark Watson
   - others?
(Note: If there's too much in the morning (depends on time needed by MTETF), we can easily push item 6 after lunch, which would give folks a chance to think about next steps.)

**Comment by chrisn** [comment]
The minutes from the 2018 F2F meeting are here: https://www.w3.org/2018/10/22-me-minutes.html
