### ISSUE TITLE
Loading development URLs on TV

### ISSUE THREAD

**Issue by anawhj** [w3c/media-and-entertainment#87]
> Enabling developer mode on a TV should allow a developer to “cast” a development server URL to the TV. It should be as simple as Chromecast has become to video playback. And TV’s need to support remote web inspector for debugging.
(https://github.com/chiefcll/media-and-entertainment/blob/master/media-dev-experience/problem-statement.md)

@chiefcll
Could you elaborate the idea above? I guess the development server URL is delivered from a host PC to a TV by a simple way so that the URL can be easily launched on TV during web app development.

**Comment by chrisn** [comment]
Some related specifications:

* DIAL http://www.dial-multiscreen.org/dial-protocol-specification
* W3C Presentation API: https://www.w3.org/TR/presentation-api/ and Open Screen Protocol https://www.w3.org/TR/openscreenprotocol/

**Comment by anawhj** [comment]
The developer mode can be supported in various ways.
Please refer to https://webostv.developer.lge.com/develop/getting-started/app-debugging for the LG webOS case.

I'm closing this thread due to lack of interests for now.
If someone has a question or opinion on this, please feel free to put it here. :)
