### ISSUE TITLE
APA Charter Acceptance and Related Proposals

### ISSUE THREAD

**Issue by JaninaSajka** [w3c/media-and-entertainment#97]
The Accessible Platform Architectures (APA) Working Group, together with our
Research Questions Task Force (RQTF) have reviewed this proposed Charter and
are pleased to support it. Only if you agree, we would prefer a formal liaison
and would like to name APA Co-Chair Janina Sajka as our liaison. We are also
agreed among ourselves that it is time for us to update the
[http://www.w3.org/TR/media-accessibility-reqs/](Media Accessibility User
Requirements (MAUR)). To that end it may be helpful to have participation from
one or more participants from the IG helping with this update, as we expect a
major revision to encompass multiple opportunities we believe to be available
now that were not available when MAUR was published in 2015. Also, if you are
in agreement, we would appreciate having this update listed in the Scope
section, i.e. <q>such as an update to the Media Accessibility User
Requirements 1.0.</q> In other words, while we will take responsibility for
MAUR and also the lead in updating this document, we would prefer to develop
the new version in close collaboration with the IG. We do note that MAUR 2.0
may also suggest certain enhancements to existing W3C specifications, or to
HTML which may be out of scope for the IG, and that APA should perhaps publish
the Note itself, but with the IG's technical support to the extentcommensurate with your Charter.

**Comment by matatk** [comment]
Thanks @chrisn. We discussed this on our APA WG call today.

We're thrilled at the prospect of collaborating on the MAUR revision with you, and thus the revised wording you propose (the second option) is the one we'd prefer.

To set expectations: as part of our MAUR revision work, we already have some things that we expect might become requests for normative changes to specs from other groups/organisations, such as WHATWG (one possibility is making a request to allow richer markup in chapter titles). Thus we may be adding things to the MAUR that we'd need other groups to help us with, which are out of MEIG's scope. However, input and review from MEIG will be vital in ensuring the success of the next MAUR.

We (specifically our Research Questions TF) would like to join an MEIG call to introduce some of the ideas we're thinking about, and we'd be happy to co-ordinate with you over email on that.

**Comment by chrisn** [comment]
Thank you @matatk, I'll update the charter accordingly, and let's coordinate on the next steps.

**Comment by chrisn** [comment]
The minutes from the MEIG meeting with APA WG are here: https://www.w3.org/2023/07/11-me-minutes.html. We have a follow up meeting at TPAC, see https://github.com/w3c/media-and-entertainment/issues/95#issuecomment-1580622323 for schedule and agenda details, and we look forward to ongoing collaboration.
